### ISSUE TITLE
Problems with require (commonjs)

### ISSUE THREAD

**Issue by erhard** [vitejs/awesome-vite#618]
I use quasar (vue3) with Vite and want to use a nom package (orbit-db) which uses requires.

in the quasar.config.js (for Vite) I have this plugin registered 

      // extendViteConf (viteConf) {},
      // viteVuePluginOptions: {},
       vitePlugins: [
         [ 'vite-plugin-require', { fileRegex:/(.js?|.tsx?|.vue)$/} ]
       ]
    },`

in the code I have 

`
import * as IPFS from 'ipfs-core'
import {onMounted} from 'vue'
const OrbitDB = require('orbit-db').   //<<this line causes the error
`

But I still get vue-router.mjs:3451 TypeError: Failed to fetch dynamically imported module: http://localhost:9000/src/pages/Orbit.vue

on the terminal output I get the following lines.  Whit do I wrong to get this module to run ?

`
App dir................ /Users/ek/orb
 » App URL................ http://localhost:9000/
                           http://10.136.76.250:9000/
 » Dev mode............... spa
 » Pkg quasar............. v2.10.2
 » Pkg @quasar/app-vite... v1.1.3
 » Browser target......... es2020

 App • Opening default browser at http://localhost:9000/

✘ [ERROR] [plugin vite:dep-pre-bundle] No known conditions for "./cid" entry in "multiformats" package

    node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:7:
      38597 │   throw new Error(
            ╵         ^

    at bail (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:8)
    at resolve (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:38654:32)
    at resolveExports (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:40982:12)
    at resolveDeepImport (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:41000:31)
    at tryNodeResolve (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:40773:20)
    at Context.resolveId (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:40581:28)
    at Object.resolveId (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:39254:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:61583:27
    at async /Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:38771:34

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-689425f3.js:38750:18:
      38750 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ ...
            ╵                   ~~~~~~~~~

    at setup (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:38750:19)
    at handlePlugins (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:855:23)
    at Object.buildOrServe (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:2109:14)
    at Object.build (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:1956:51)
    at runOptimizeDeps (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:39994:34)
    at async runOptimizer (/Users/ek/orb/node_modules/vite/dist/node/chunks/dep-689425f3.js:50529:38)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/orbit-db/src/orbit-db-address.js:3:24:
      3 │ const { CID } = require('multiformats/cid')
        ╵                         ~~~~~~~~~~~~~~~~~~

17:18:30 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:7: ERROR: [plugin: vite:dep-pre-bundle] No known conditions for "./cid" entry in "multiformats" package
    at failureErrorWithLog (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:1264:7)
    at /Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:1377:14
    at /Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/ek/orb/node_modules/vite/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
Vite Error, /node_modules/.q-cache/vite/spa/deps/orbit-db.js?v=2fcde633 optimized info should be defined
Vite Error, /node_modules/.q-cache/vite/spa/deps/orbit-db.js?v=2fcde633 optimized info should be defined
`

**Comment by erhard** [comment]
closed because opened in vite opened #11139
